### ISSUE TITLE
我用这个代码 模拟用户建房 为什么 查看房间活跃度并不计算  是否 用代码创建的房间 都是不计入活跃度的

### ISSUE THREAD

**Issue by nankedou** [xaniyaa/d2bot#3]

**Comment by meyafex** [comment]
It's a bit complicated to understand Chinese with translator. Write on english next time

**Comment by nankedou** [comment]
We are currently developing a Dota 2 arcade game. I intend to simulate account login and room creation through code in order to automatically start matches and increase the number of active players in the game. Using your provided code, I have been able to successfully log in to accounts. However, the number of active players does not increase ingame through code. If these simulated logins are not being counted, what should I do to automatically create a significant number of active players?

**Comment by meyafex** [comment]
You can use dota.get_lobby_list(), that will give you a container with all lobbies, and with "players" variable, next step is just to find your lobby and get amount of players. You can use dota.sleep(int(seconds)) to wait a little bit till next lobby list update

**Comment by nankedou** [comment]
I am simulating Player A and Player B logging in with code. Player A creates a room and invites Player B to join the room, and then the game starts. Can Player A and Player B battle against each other? Currently, both players are in the same room but cannot click on the confirmation button.




Question 1: How can I start the game battle?&nbsp;
Question 2: Can I increase the number of players on the map in this simulated battle, as shown in the image?&nbsp;
Question 3: I would like to simulate a battle with players using code. I’m not sure if this functionality is possible, and whether it’s feasible to increase the number of players in this way















芦鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaniyaa/d2bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 上午6:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xaniyaa/d2bot] 我用这个代码 模拟用户建房 为什么 查看房间活跃度并不计算  是否 用代码创建的房间 都是不计入活跃度的 (Issue #3)





 
You can use dota.get_lobby_list(), that will give you a container with all lobbies, and with "players" variable, next step is just to find your lobby and get amount of players. You can use dota.sleep(int(seconds)) to wait a little bit till next lobby list update

**Comment by meyafex** [comment]
I am not sure how Player B can accept the game if you mean that 2 players are programs. Unfortunately, I can't see images, so I can't understand what you mean, but right in the game with enabled cheats you can spawn bot's, other players C or players D after the game start can't join it anymore. If you can provide me some code that I can look at, it should be easier to test, because it is very hard to find info about dota2api.

**Comment by nankedou** [comment]
Do you have any contact information?




芦鹏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xaniyaa/d2bot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月13日(星期四) 晚上9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xaniyaa/d2bot] 我用这个代码 模拟用户建房 为什么 查看房间活跃度并不计算  是否 用代码创建的房间 都是不计入活跃度的 (Issue #3)





 
I am not sure how Player B can accept the game if you mean that 2 players are programs. Unfortunately, I can't see images, so I can't understand what you mean, but right in the game with enabled cheats you can spawn bot's, other players C or players D after the game start can't join it anymore. If you can provide me some code that I can look at, it should be easier to test, because it is very hard to find info about dota2api.

**Comment by meyafex** [comment]
@sndmndss is my telegram

**Comment by nankedou** [comment]
I am simulating Player A and Player B logging in with code. Player A creates a room and invites Player B to join the room, and then the game starts. Can Player A and Player B battle against each other? Currently, both players are in the same room but cannot click on the confirmation button.


Question 1: How can I start the game battle?
Question 2: Can I increase the number of players on the map in this simulated battle, as shown in the image?
Question 3: I would like to simulate a battle with players using code. I’m not sure if this functionality is possible, and whether it’s feasible to increase the number of players in this way

![image](https://github.com/xaniyaa/d2bot/assets/16421456/8a119b34-e75d-4d44-ba4f-13815d55b887)
![image](https://github.com/xaniyaa/d2bot/assets/16421456/8a5c88af-abb1-4712-a621-298a0e627f1c)

**Comment by meyafex** [comment]
Or you can reach write me right on steam, what messenger will be better for you?

**Comment by nankedou** [comment]
steamid 多少？

**Comment by meyafex** [comment]
76561198044532481

**Comment by nankedou** [comment]
加你了

**Comment by meyafex** [comment]
I have no invites, maybe you have 0 level steam, send me your id

**Comment by nankedou** [comment]
https://steamcommunity.com/profiles/76561198423627213/friends

**Comment by nankedou** [comment]
![image](https://github.com/xaniyaa/d2bot/assets/16421456/565dcfde-4f38-4734-b937-6550160d2657)
